on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
#
env:
  GHIDRA_ARCHIVE: https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.4_build/ghidra_10.4_PUBLIC_20230928.zip
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
#
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    #
    permissions:
      contents: read
      packages: write
    #
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      #
      - name: Login to registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      #
      - name: Grab metadata
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      #
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      #
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      #
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            GHIDRA_ARCHIVE=${{ env.GHIDRA_ARCHIVE }}