name: Run updatecli

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}

    - name: Install Updatecli in the runner
      uses: updatecli/updatecli-action@v2

    - name: Run updatecli in apply mode
      run: updatecli apply

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update dependencies with updatecli"